server:
  port : 8080

crypto:
  supported_list: BTC,DOGE,ETH,LTC,XRP

#rate limit settings
bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      filter-method: servlet
      rate-limits:
        - expression: "getRemoteAddr()"
          bandwidths:
            - capacity: 100
              time: 1
              unit: minutes

spring:
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

